CREATE TABLE links
(
    id          SERIAL PRIMARY KEY,
    original    VARCHAR(255) UNIQUE NOT NULL,
    short       VARCHAR(255) UNIQUE NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
